branch-defaults:
  master:
    environment: AvatarProduction-env
environment-defaults:
  AvatarProduction-env:
    branch: null
    repository: null
global:
  application_name: avatar-production
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
